### ISSUE TITLE
Рассмотреть возможность включения в список offline-документации Битрикса

### ISSUE THREAD

**Issue by antonvorobyev** [awesomebitrix/awesome-bitrix#1]

**Comment by gromdron** [comment]
Мое личное мнение - не стоит включать offline документацию в репозиторий.
Во-первых, online документация обновляется быстрее и наиболее точно отражает действительность
Во-вторых, offline документация (см. еще пункт выше) устаревает быстрее и перестает обновляться (Пример: файл с сравнением Битрикс24 и SharePoint основывается на версии КП 8.0 и не поддерживается с тех самых пор). 

Не думаю, что 1С-Битрикс будет поддерживать (создавать новые и обновлять существующие) все существующие типы документации.

**Comment by antonvorobyev** [comment]
@gromdron принято, согласен.
