### ISSUE TITLE
Добавить забытое

### ISSUE THREAD

**Issue by may-cat** [awesomebitrix/awesome-bitrix#10]
В список https://github.com/awesomebitrix/awesome-bitrix нужно внести 
* bbc.bitrix.expert - Базовые Битрикс Компоненты
* AdminHelper 
- это удобнейшие ООП-инструменты для быстрой сборки публички и админки

Посмотрите, пожалуйста, также
http://bitrix.expert/opensource/perspektivnye-otkrytye-resheniya/index.html

**Comment by antonvorobyev** [comment]
@may-cat благодарю за рекомендации!

**Comment by antonvorobyev** [comment]
@may-cat рекомендации добавлены в список.
